### ISSUE TITLE
"--test-warnings" doesn't work because there's no config named that

### ISSUE THREAD

**Issue by palfrey** [landscapeio/prospector#151]
`prospector --test-warnings` gets me                                                                                                                       
Failed to run:
Could not find profile test_warnings. Search path: /Users/palfrey/src/potboiler/python:/Users/palfrey/src/potboiler/python/ENV/lib/python3.5/site-packages/prospector/profiles/profiles

Assuming this is because there is no "test_warnings" config. Found a "no_test_warnings" config, but not one to include it, so it's kinda weird there's this config option that doesn't work...

**Comment by deadzero** [comment]
Bump. I tired to create one based on the no_doc_warnings.yaml and doc_warnings.yaml, so I created a test_warnings.yaml: `allow-shorthand: false` which removes the error but doesn't seem to check the test files.

Is there a way to remove profiles I assume removing the no_doc_warnings and no_test_warning would accomplish the same?

**Comment by carlio** [comment]
Fixed now, released in 0.12 :+1:

**Comment by palfrey** [comment]
Bug is still there, because the file is called "test_warnings.yml" not "test_warnings.yaml" and so didn't get included in the package.

**Comment by carlio** [comment]
Fixed properly this time, now in 0.12.1... sorry for the delay
